language: node_js
node_js:
  - "6"
  - "5"
  - "4"

sudo: false

os:
  - linux
  - os: osx

osx_image: xcode7.2

before_install:
  - node --version
  - npm --version
  - gcc --version

script:
  - npm install

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
